### ISSUE TITLE
Unable to compile with nimble_options 0.5.2

### ISSUE THREAD

**Issue by axelson** [am-kantox/finitomata#114]
I tried adding finitomata into a relatively simple project (https://github.com/axelson/pomodoro) and I get a compilation error:
```
==> finitomata
Compiling 33 files (.ex)

== Compilation error in file lib/finitomata/cache.ex ==
** (ArgumentError) invalid NimbleOptions schema. Reason: invalid value for :type option: invalid type given to :or type: unknown type nil.

Available types: :any, :keyword_list, :non_empty_keyword_list, :map, :atom, :integer, :non_neg_integer, :pos_integer, :float, :mfa, :mod_arg, :string, :boolean, :timeout, :pid, :reference, {:fun, arity}, {:in, choices}, {:or, subtypes}, {:custom, mod, fun, args}, {:list, subtype}, {:tuple, list_of_subtypes}, {:map, key_type, value_type}, {:struct, struct_name} (in options [:getter])
    (nimble_options 0.5.2) lib/nimble_options.ex:350: NimbleOptions.new!/1
    lib/finitomata/cache.ex:166: (module)
could not compile dependency :finitomata, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile finitomata --force", update it with "mix deps.update finitomata" or clean it with "mix deps.clean finitomata"
```

I'm using finitomata 0.26.3 and nimble_options 0.5.2 so maybe they're not compatible. Upgrading to nimble_options 1.1.1 allows compilation to succeed.

**Comment by vlemann** [comment]
As per `NimbleOptions` [docs](https://hexdocs.pm/nimble_options/NimbleOptions.html#module-types), `nil` type is indeed available since `1.0`.

We’ll introduce a fix conditionally checking for a version of `NimbleOptions` used. Stay tuned.

What would be the reason to stay with `0.5.2` btw? `1.0` is a version bump, it’s fully backward compatible.

**Comment by vlemann** [comment]
> Package published to https://hex.pm/packages/finitomata/0.26.4
> (5b19f84a8501bead4a0c39b6d34d17e3211ff4e8ed9d1fdcb1fd31d4a36d0f2a)

**Comment by axelson** [comment]
> Package published to https://hex.pm/packages/finitomata/0.26.4
> (5b19f84a8501bead4a0c39b6d34d17e3211ff4e8ed9d1fdcb1fd31d4a36d0f2a)

Awesome, thank you!

> What would be the reason to stay with 0.5.2 btw? 1.0 is a version bump, it’s fully backward compatible.

Ah, the main reason was because I was waiting for https://github.com/boydm/font_metrics/pull/8 to be merged (I try quite hard to avoid `override: true` when possible). But I realized that I do have the ability to publish a new release, so I went ahead and did that by releasing `font_metrics` 0.5.2 which supports NimbleOptions `~> 1.0`.
